apiVersion: v1                  
name: service-tensorflow             # 어떠한 서비스인가에 대한 정의를 내려줄 것 (ex. service-tensorflow, service-nginx)
                                # 위 정보는 Deployment-Container 이름정보 뒷부분에에 매칭되어 표기됨!    
version: 0.1.0                  # 차트 버전관리/ 차트 내용수정 및 업그레이드 시 변경 (관리자가 관리하는 부분)
appVersion: _img           # 가져올 이미지명으로 커스터마이징함 [[repository/{appVersion} 으로보면됨]]
description: tensorflow helm test    # 차트에대한 상세설명
