## Deployment Part ##
name: it                    # 고객구분을 위한 고객명으로 입력할것 (--set옵션으로 수정배포 가능)// 향후 네임스페이스명과 동일하게 갈것
label: it-tensorflow             # HPE고객에서 사용하는 Nginx 서비스라는것을 알수있게 [고객명(name)-서비스명으로 생성] 
replicaCount: 1                 

image:
  repository: jiyeon9569     # 가져올 Dockerhub repo명
  pullPolicy: Always
  name: ""                    # 디폴트값은 Chart.yaml의 appVersion을 따름

cpu: 
  limits: 2
  requests: 1

memory: 
  limits: 2000Mi                 # Mi, Gi 등 단위 설정해서 기입
  requests: 1000Mi
 
volume:
  name: it-tensorflow           # 생성할 볼륨 이름
  path: /data               # 마운트 경로 (ex. /usr/share/nginx)
  claim: tensor-volume     # PVC 이름

## Service Part ##  
service:
  type: ""                   # service.yaml에 default값 LoadBalancer로 기입되어있음. 다른용도일시 변경필요.
  sshport: 22                # 외부노출 ssh 포트 (포트포워딩용)
  
annotations:
  group: gpu                 # 디폴트 Metal-lb  IP-pool은 default이며, --set옵션으로 변경가능
   
