apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    client: {{ .Values.name }}                        # Deployment에 붙여지는 Client Label 정보 >> client = .Valuse.Name (고객명). 해당 DP에서 생성되는 POD들과 매칭할 Label정보
  name: {{ .Values.name }}:{{ .Values.service }}      # DP 리스트로 구분할 수 있는 메타데이터 [고객:서비스로 구분] (결과물은 Name : deployment.app/{Values.Name} 으로 확인가능)
spec:
  replicas: {{ .Values.replicaCount }}                # 복제본 개수 (default는 1로 설정)
  selector:
    matchLabels:
      service: {{ .Values.service }}                  # spec.selector.matchLabels 필드는 디플로이먼트가 관리할 Pod를 찾는 방법을 정의.
  template:
    metadata:
      labels:
        service: {{ .Values.service }}                # 디플로이먼트에서 생성하는 Pod에 붙일 레이블명으로 위 spec.selector.matchLabels와 동일하게함
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{- if .Values.image.tag }}{{ .Values.image.tag }}{{- end }}   # {Repository}/{이미지이름}:{Tag}
        name: {{ .Values.name }}-{{ .Values.image.name }}                      # 컨테이너에 붙을 이름. 결과적으로 {고객명}-{이미지이름}으로 작성
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}     # 재생성시 이미지를 어떻게가져올것인지 규칙 선택
        resources:
          requests:                                   # resources의 cpu는 core(개) 단위로 보통 할당하지만 소숫점단위 0.x로도 가능
            cpu: "{{ .Values.cpu.requests }}"         # resources의 memory는 단위를 지정해주는것이 보통 Mi or Gi
            memory: "{{ .Values.memory.requests }}"
          limits:
            cpu: "{{ .Values.cpu.limits }}"
            memory: "{{ .Values.memory.limits }}"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.sshport }}
            initialDelaySeconds: 5
            periodSeconds: 5
        ports: 
          - containerPort: 8888
            name: jupyter                            # 주피터 노트북 사용시 8888 포트도 오픈할것
          - containerPort: 22
            name: ssh
        volumeMounts:
          - name: {{ .Values.volume.name }}          # spec.template.volumes에서 선언한 볼륨 name을 컨테이너에 가져와서 사용
            mountPath: {{ .Values.volume.path }}     # 실제 생성하는 컨테이너안에서 확인 할 수 있는 Mount 경로    
      {{- if .Values.GPU.enabled }}                  # GPU 사용 enable 시, 노드어피니티 및 테인트/톨러레이션 사용
      affinity:
        nodeAffinity:
          requiredDuringSchedulingExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: Nodetype
                operator: In
                values:
                - GPU
      toleration:
      - key: {{ .Values. }}
        operator: {{ .Values. }}
        effect: {{ .Values. }}
      {{- else }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingExecution:
            preference:
            - matchExpressions:
              - key: Nodetype
                operator: In
                values:
                - CPU
      {{- end -}}
      volumes:
      - name: {{ .Values.volume.name }}             # 사용할 volume을 정의. 이름 생성 >> volumeMounts아래 필드에서 사용할 수 있도록 선언해줌
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default .Values.volume.claim }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
